name: soc-lab-suricata

services:
  victim:
    image: python:3-alpine
    container_name: suricata-victim
    command: python /app/victim.py
    volumes:
      - D:/soc-lab/config/suricata/scripts:/app:ro
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1',80))"]
      interval: 2s
      timeout: 2s
      retries: 30

  attacker:
    image: python:3-alpine
    container_name: suricata-attacker
    command: python /app/attacker.py
    volumes:
      - D:/soc-lab/config/suricata/scripts:/app:ro
    networks:
      - intranet
    depends_on:
      victim:
        condition: service_healthy

  suricata:
    image: jasonish/suricata:7.0
    container_name: suricata-sniffer
    network_mode: service:victim
    depends_on:
      - victim
    command:
      - -i
      - eth0
      - -S
      - /etc/suricata/rules/local.rules
    volumes:
      - D:/soc-lab/config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
      - D:/soc-lab/config/suricata/rules/local.rules:/etc/suricata/rules/local.rules:ro
      - D:/soc-lab/data/suricata/logs:/var/log/suricata
    restart: on-failure

networks:
  intranet:
    driver: bridge