name: cloud-siem-suricata

services:
  victim:
    image: python:3-alpine
    container_name: suricata-victim
    command: python /app/victim.py
    volumes:
      - ./scripts:/app:ro
    networks:
      - intranet

  attacker:
    image: python:3-alpine
    container_name: suricata-attacker
    command: python /app/attacker.py
    volumes:
      - ./scripts:/app:ro
    networks:
      - intranet
    depends_on:
      - victim
      - suricata

  suricata:
    image: jasonish/suricata:7.0
    container_name: suricata-sniffer
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    networks:
      - intranet
    command:
      - -i
      - eth0
      - -S
      - /etc/suricata/rules/local.rules
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml:ro
      - ./rules/local.rules:/etc/suricata/rules/local.rules:ro
      - ../../data/suricata/logs:/var/log/suricata
    restart: on-failure

  filebeat:
    image: elastic/filebeat:8.12.0
    container_name: suricata-filebeat
    user: root
    volumes:
      - ../filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../../data/suricata/logs:/var/log/suricata:ro
    depends_on:
      - suricata
    networks:
      - intranet
    restart: on-failure

networks:
  intranet:
    driver: bridge
