apiVersion: 1

datasources:
  - name: Wazuh Indexer
    type: grafana-opensearch-datasource
    access: proxy
    url: https://wazuh.indexer:9200
    isDefault: true
    jsonData:
      database: wazuh-alerts-*
      flavor: opensearch
      logMessageField: full_log
      logLevelField: rule.level
      ssl:
        verify: false
      timeField: timestamp
      version: 2.12.0
    secureJsonData:
      password: SecretPassword
    editable: true

  - name: Suricata Indexer
    type: grafana-opensearch-datasource
    access: proxy
    url: https://wazuh.indexer:9200
    jsonData:
      database: suricata-*
      flavor: opensearch
      logMessageField: alert.signature
      logLevelField: alert.severity
      ssl:
        verify: false
      timeField: timestamp
      version: 2.12.0
    secureJsonData:
      password: SecretPassword
    editable: true
